channels:
  - bioconda
  - conda-forge
dependencies:
  - snakemake-minimal
  - graphviz
  - python =3.6
  - gatk4 =4.0.11.0
  - hisat2 =2.1.0
  - samtools =1.9
  - sra-tools=2.10.8
  - stringtie
  - biopython
  - git
  - maven
  - fastqc
  - skewer
  - numpy =1.16.4
  - biopython
  - bcbio-gff
  - pandas
